channels:
  - conda-forge
  - default
dependencies:
  - python=3.10
  - pytest=8.3.2
  - flake8=7.1.1
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - requests=2.32.3
  - fastapi=0.112.1
  - uvicorn=0.30.6